/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity and scope of the authenticated token */
        get: operations["getCurrentIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * List tickets in a project
         * @description Mirrors the list_tickets MCP tool. Items are verbosity-projected ticket objects.
         */
        get: operations["listTickets"];
        put?: never;
        /** Create a ticket */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Search tickets (text, semantic, or hybrid) */
        get: operations["searchTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** Get a ticket with comments and links */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        /** Delete a ticket and all its related data */
        delete: operations["deleteTicket"];
        options?: never;
        head?: never;
        /** Update a ticket's fields */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a ticket to in_progress */
        post: operations["startTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a ticket as done */
        post: operations["completeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a ticket */
        post: operations["cancelTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a ticket back to the open queue */
        post: operations["reopenTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a comment to a ticket */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** Get a ticket's link graph up to N hops */
        get: operations["getTicketGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets/{ticketId}/dependency-graph": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** Render a ticket dependency graph (text tree + nodes/edges) */
        get: operations["renderDependencyGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/links": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link two tickets (blocks, relates_to, duplicates) */
        post: operations["linkTickets"];
        /**
         * Remove a link between two tickets
         * @description Identifies the link via a JSON request body. Some proxies strip DELETE bodies; ensure your client sends it.
         */
        delete: operations["unlinkTickets"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Ticket counts grouped by status, type, and priority */
        get: operations["getProjectStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List tags in use with their ticket counts */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/board": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Render a kanban board (markdown) grouped by status, priority, or type */
        get: operations["renderTicketBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations you belong to */
        get: operations["listOrganizations"];
        put?: never;
        /** Create an organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete an organization and all its projects */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        /** Update an organization's name or slug */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/organizations/{orgSlug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        /** List members and pending invitations for an organization */
        get: operations["listOrganizationMembers"];
        put?: never;
        /** Create an invitation link to an organization */
        post: operations["inviteOrganizationMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from an organization */
        delete: operations["removeOrganizationMember"];
        options?: never;
        head?: never;
        /** Change a member's role in an organization */
        patch: operations["updateOrganizationMemberRole"];
        trace?: never;
    };
    "/organizations/{orgSlug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        /** List projects in an organization */
        get: operations["listProjects"];
        put?: never;
        /** Create a project in an organization */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}/projects/{projectSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Schedule a project for deletion (30-day retention) */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Change a project's key prefix */
        patch: operations["setProjectKeyPrefix"];
        trace?: never;
    };
    "/organizations/{orgSlug}/projects/{projectSlug}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending project deletion */
        post: operations["restoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}/projects/{projectSlug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        /** List members assigned to a project */
        get: operations["listProjectMembers"];
        put?: never;
        /** Add an organization member to a project */
        post: operations["addProjectMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}/projects/{projectSlug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a project */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        /** Change a member's role on a project */
        patch: operations["updateProjectMemberRole"];
        trace?: never;
    };
    "/organizations/{orgSlug}/projects/{projectSlug}/github-repos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        /** List GitHub repositories linked to a project */
        get: operations["listGithubRepos"];
        put?: never;
        /** Link a GitHub repository to a project */
        post: operations["linkGithubRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgSlug}/github-repos/{mappingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Repository mapping ID from listGithubRepos. */
                mappingId: components["parameters"]["MappingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a GitHub repository from a project */
        delete: operations["unlinkGithubRepo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Status: "open" | "in_progress" | "done" | "cancelled";
        /** @enum {string} */
        TicketType: "chore" | "bug" | "feature" | "epic";
        /** @enum {string} */
        Priority: "low" | "medium" | "high" | "urgent";
        /** @enum {string} */
        LinkType: "blocks" | "relates_to" | "duplicates";
        /** @enum {string} */
        SearchMode: "text" | "semantic" | "hybrid";
        /** @enum {string} */
        SortField: "created_at" | "updated_at" | "completed_at" | "due_date" | "priority" | "status" | "type" | "title";
        /** @enum {string} */
        SortDirection: "asc" | "desc";
        /** @enum {string} */
        GroupBy: "status" | "priority" | "type";
        /** @enum {string} */
        Verbosity: "short" | "detailed" | "full";
        /** @enum {string} */
        OrgRole: "owner" | "admin" | "member";
        /** @enum {string} */
        OrgInviteRole: "admin" | "member";
        /** @enum {string} */
        ProjectRole: "admin" | "editor" | "viewer";
        /** @enum {string} */
        OrgPlan: "free" | "pro" | "enterprise";
        Error: {
            error: string;
            details?: unknown[];
        };
        Identity: {
            user: {
                id: string;
                email: string;
                name: string;
            };
            token: {
                /** @enum {string} */
                scope: "user" | "project";
                /** @enum {string} */
                accessLevel: "read" | "read_write";
                projectId: string | null;
            };
        };
        /** @description A ticket. `key`/`number` are present once the project has a key prefix; `similar_tickets` may appear on create. */
        Ticket: {
            id: string;
            title: string;
            description: string;
            status: components["schemas"]["Status"];
            type: components["schemas"]["TicketType"];
            priority: components["schemas"]["Priority"];
            estimate: string | null;
            actual: string | null;
            tags: string[];
            parent_ticket_id: string | null;
            assignee: string | null;
            due_date: string | null;
            created_at: string;
            updated_at: string;
            completed_at: string | null;
            metadata: {
                [key: string]: unknown;
            };
            key?: string | null;
            number?: number | null;
            similar_tickets?: {
                key: string | null;
                title: string;
                potential_duplicate?: boolean;
            }[];
        };
        /** @description A verbosity-projected ticket. `short` returns id, title, status, type, priority, estimate, tags, due_date, assignee; `detailed` returns the full ticket with a truncated description; `full` returns the complete ticket. Always includes `key`/`number` when available, and `score` on search results. */
        TicketView: {
            [key: string]: unknown;
        };
        TicketComment: {
            id: string;
            ticket_id: string;
            content: string;
            created_at: string;
            created_by: string;
        };
        TicketLink: {
            id: string;
            source_ticket_id: string;
            target_ticket_id: string;
            link_type: components["schemas"]["LinkType"];
            created_at: string;
        };
        /** @description A verbosity-projected ticket plus a `comments` array (TicketComment[]) and a `links` array (TicketLink[]), and optionally `history` (TicketHistory[]) and `subtickets` (TicketView[]) when requested via the include_history / include_subtickets query flags. */
        TicketDetail: {
            [key: string]: unknown;
        };
        TicketList: {
            tickets: components["schemas"]["TicketView"][];
            total: number;
        };
        TicketGraph: {
            nodes: components["schemas"]["TicketView"][];
            edges: components["schemas"]["TicketLink"][];
        };
        DependencyGraph: {
            text: string;
            nodes: components["schemas"]["TicketView"][];
            edges: components["schemas"]["TicketLink"][];
        };
        ProjectStats: {
            total: number;
            byStatus: {
                [key: string]: number;
            };
            byType: {
                [key: string]: number;
            };
            byPriority: {
                [key: string]: number;
            };
        };
        TagCount: {
            tag: string;
            count: number;
        };
        Board: {
            board: string;
        };
        Deleted: {
            deleted: boolean;
        };
        DeletedTicket: {
            deleted: boolean;
            id: string;
        };
        DeletedSlug: {
            deleted: boolean;
            slug: string;
        };
        RestoredSlug: {
            restored: boolean;
            slug: string;
        };
        Organization: {
            id: string;
            name: string;
            slug: string;
            plan: components["schemas"]["OrgPlan"];
            role: components["schemas"]["OrgRole"];
            createdAt: string;
            deleteRequestedAt: string | null;
            subscriptionActive: boolean;
        };
        OrganizationBasic: {
            id: string;
            name: string;
            slug: string;
            plan: components["schemas"]["OrgPlan"];
            createdAt: string;
        };
        OrganizationList: {
            count: number;
            organizations: components["schemas"]["Organization"][];
        };
        OrgMember: {
            userId: string;
            role: components["schemas"]["OrgRole"];
            joinedAt: string;
            email: string;
            name: string;
            avatarUrl: string | null;
        };
        Invitation: {
            id: string;
            email: string;
            role: components["schemas"]["OrgInviteRole"];
            expiresAt: string;
            token?: string;
            invitationUrl?: string;
            message?: string;
        };
        OrgMemberList: {
            members: components["schemas"]["OrgMember"][];
            pendingInvitations: components["schemas"]["Invitation"][];
        };
        MemberRoleUpdated: {
            updated: boolean;
            userId: string;
            role: components["schemas"]["OrgInviteRole"];
        };
        MemberRoleUpdatedProject: {
            updated: boolean;
            userId: string;
            role: components["schemas"]["ProjectRole"];
        };
        MemberRemoved: {
            removed: boolean;
            userId: string;
        };
        Project: {
            id: string;
            name: string;
            slug: string;
            keyPrefix: string | null;
            createdAt: string;
            role?: components["schemas"]["ProjectRole"];
        };
        ProjectBasic: {
            id: string;
            name: string;
            slug: string;
            keyPrefix: string | null;
            createdAt: string;
        };
        ProjectList: {
            count: number;
            projects: components["schemas"]["Project"][];
        };
        ProjectMember: {
            userId: string;
            role: components["schemas"]["ProjectRole"];
            email: string;
            name: string;
            avatarUrl: string | null;
        };
        ProjectMemberList: {
            count: number;
            members: components["schemas"]["ProjectMember"][];
        };
        ProjectMemberAdded: {
            added: boolean;
            userId: string;
            role: components["schemas"]["ProjectRole"];
        };
        KeyPrefixUpdated: {
            project_id: string;
            slug: string;
            key_prefix: string;
            previous_prefix: string | null;
        };
        GithubRepo: {
            id: string;
            owner: string;
            repo: string;
            fullName: string;
            createdAt: string;
        };
        /** @description `{ count: number, repos: GithubRepo[] }` — the GitHub repositories linked to the project. */
        GithubRepoList: {
            [key: string]: unknown;
        };
        /** @description On success: { ok: true, mapping_id, repo, message } or { ok: true, already_linked: true, mapping_id }. Recoverable failures carry an `error` discriminator (github_not_connected, insufficient_github_scope, github_org_restriction) with guidance fields. */
        GithubLinkResult: {
            [key: string]: unknown;
        };
        /** @description `{ ok: true, unlinked: "owner/repo" }` — the repository mapping that was removed. */
        GithubUnlinkResult: {
            [key: string]: unknown;
        };
        CreateTicketBody: {
            title: string;
            description?: string;
            status?: components["schemas"]["Status"];
            type?: components["schemas"]["TicketType"];
            priority?: components["schemas"]["Priority"];
            estimate?: string;
            tags?: string[];
            parent_ticket_id?: string;
            assignee?: string;
            due_date?: string;
            metadata?: {
                [key: string]: unknown;
            };
            links?: {
                target_ticket_id: string;
                link_type: components["schemas"]["LinkType"];
            }[];
            initial_comment?: string;
        };
        UpdateTicketBody: {
            title?: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            priority?: components["schemas"]["Priority"];
            estimate?: string | null;
            tags?: string[];
            parent_ticket_id?: string | null;
            assignee?: string | null;
            due_date?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
        };
        CompleteTicketBody: {
            actual?: string;
        };
        AddCommentBody: {
            content: string;
        };
        LinkTicketsBody: {
            source_ticket_id: string;
            target_ticket_id: string;
            link_type: components["schemas"]["LinkType"];
        };
        CreateOrgBody: {
            name: string;
        };
        UpdateOrgBody: {
            name?: string;
            slug?: string;
        };
        InviteMemberBody: {
            /** Format: email */
            email: string;
            role: components["schemas"]["OrgInviteRole"];
        };
        OrgMemberRoleBody: {
            role: components["schemas"]["OrgInviteRole"];
        };
        CreateProjectBody: {
            name: string;
            key_prefix?: string;
        };
        KeyPrefixBody: {
            key_prefix: string;
        };
        AddProjectMemberBody: {
            /** Format: uuid */
            user_id: string;
            role: components["schemas"]["ProjectRole"];
        };
        ProjectMemberRoleBody: {
            role: components["schemas"]["ProjectRole"];
        };
        LinkGithubRepoBody: {
            /** @description GitHub repository in `owner/repo` form. */
            repo: string;
        };
    };
    responses: {
        /** @description The request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, malformed, revoked, or expired API secret. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The secret lacks permission (read-only on a write, wrong scope, insufficient role). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The addressed resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The project ID (UUID). */
        ProjectId: string;
        /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
        TicketId: string;
        /** @description Organization slug. */
        OrgSlug: string;
        /** @description Project slug. */
        ProjectSlug: string;
        /** @description Target member's user ID (UUID). */
        UserId: string;
        /** @description Repository mapping ID from listGithubRepos. */
        MappingId: string;
        /** @description Filter by one or more statuses. */
        QStatus: components["schemas"]["Status"][];
        /** @description Filter by one or more types. */
        QType: components["schemas"]["TicketType"][];
        /** @description Filter by one or more priorities. */
        QPriority: components["schemas"]["Priority"][];
        /** @description Filter by one or more tags. */
        QTags: string[];
        /** @description Projection detail level. */
        QVerbosity: components["schemas"]["Verbosity"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                /** @description Filter by one or more statuses. */
                status?: components["parameters"]["QStatus"];
                /** @description Filter by one or more types. */
                type?: components["parameters"]["QType"];
                /** @description Filter by one or more priorities. */
                priority?: components["parameters"]["QPriority"];
                /** @description Filter by one or more tags. */
                tags?: components["parameters"]["QTags"];
                parent_ticket_id?: string;
                assignee?: string;
                created_after?: string;
                created_before?: string;
                completed_after?: string;
                completed_before?: string;
                due_after?: string;
                due_before?: string;
                sort?: components["schemas"]["SortField"];
                sort_direction?: components["schemas"]["SortDirection"];
                limit?: number;
                offset?: number;
                /** @description Projection detail level. */
                verbosity?: components["parameters"]["QVerbosity"];
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    searchTickets: {
        parameters: {
            query: {
                query: string;
                mode?: components["schemas"]["SearchMode"];
                /** @description Filter by one or more statuses. */
                status?: components["parameters"]["QStatus"];
                /** @description Filter by one or more types. */
                type?: components["parameters"]["QType"];
                /** @description Filter by one or more priorities. */
                priority?: components["parameters"]["QPriority"];
                limit?: number;
                /** @description Projection detail level. */
                verbosity?: components["parameters"]["QVerbosity"];
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketView"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getTicket: {
        parameters: {
            query?: {
                include_history?: boolean;
                include_subtickets?: boolean;
                /** @description Projection detail level. */
                verbosity?: components["parameters"]["QVerbosity"];
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    completeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompleteTicketBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reopenTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketComment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getTicketGraph: {
        parameters: {
            query?: {
                depth?: number;
                /** @description Projection detail level. */
                verbosity?: components["parameters"]["QVerbosity"];
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketGraph"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    renderDependencyGraph: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
                /** @description Ticket ULID or project-scoped key (e.g. WD-42). */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyGraph"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    linkTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkTicketsBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketLink"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unlinkTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkTicketsBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getProjectStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCount"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    renderTicketBoard: {
        parameters: {
            query?: {
                group_by?: components["schemas"]["GroupBy"];
                /** @description Filter by one or more statuses. */
                status?: components["parameters"]["QStatus"];
                /** @description Filter by one or more types. */
                type?: components["parameters"]["QType"];
                /** @description Filter by one or more priorities. */
                priority?: components["parameters"]["QPriority"];
                /** @description Filter by one or more tags. */
                tags?: components["parameters"]["QTags"];
            };
            header?: never;
            path: {
                /** @description The project ID (UUID). */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationBasic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedSlug"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationBasic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listOrganizationMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    inviteOrganizationMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeOrganizationMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRemoved"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrganizationMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgMemberRoleBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRoleUpdated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectBasic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedSlug"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setProjectKeyPrefix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyPrefixBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyPrefixUpdated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    restoreProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoredSlug"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjectMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberAdded"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRemoved"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProjectMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
                /** @description Target member's user ID (UUID). */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberRoleBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRoleUpdatedProject"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGithubRepos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubRepoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    linkGithubRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Project slug. */
                projectSlug: components["parameters"]["ProjectSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkGithubRepoBody"];
            };
        };
        responses: {
            /** @description Recoverable outcome (e.g. already linked, GitHub not connected) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubLinkResult"];
                };
            };
            /** @description A new repository mapping was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubLinkResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unlinkGithubRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization slug. */
                orgSlug: components["parameters"]["OrgSlug"];
                /** @description Repository mapping ID from listGithubRepos. */
                mappingId: components["parameters"]["MappingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubUnlinkResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
